### ISSUE TITLE
Adding env support for conda

### ISSUE THREAD

**Issue by crazy4pi314** [tonybaloney/CSnakes#183]
I have gotten conda envs to work with csnakes by specifying hard paths with the `FromFolder` and `WithVirtualEnvironment` options on the source builder. I wanted to document the different ways I think these paths can be found programmatically from the [conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html) with example output:

```
> echo $env:CONDA_PREFIX
C:\Users\sarahkaiser\Anaconda3

> conda env list --json
{
  "envs": [
    "C:\\Users\\sarahkaiser\\Anaconda3",
    "C:\\Users\\sarahkaiser\\Anaconda3\\envs\\csnakes",
    "C:\\Users\\sarahkaiser\\Anaconda3\\envs\\distats-bot",
    "C:\\Users\\sarahkaiser\\micromambaenv\\envs\\dask-tutorial-advanced",
    "c:\\Users\\sarahkaiser\\Anaconda3\\envs\\ghstats"
  ]
}
```
You will note that conda does list envs that are at a different base prefix since I also have micromamba installed.

If the env I was looking for was csnakes it would be at:
```
> $(conda info --base)/envs/csnakes
```

**Comment by tonybaloney** [comment]
Implemented in #232
