### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by aaronpowell** [tonybaloney/CSnakes#193]
We have only done C# support and tested with C# samples. We should explore what the F# support is like and ensure it is at least somewhat usable from F#.

**Comment by AaronRobinsonMSFT** [comment]
Note that Roslyn source generators are only for C# and VB.NET. The F# compiler is its own beast, which means the a [stand alone tool](https://github.com/tonybaloney/CSnakes/pull/195) is likely needed.

**Comment by aaronpowell** [comment]
Yeah, if we really want F# support I'd look at a type provider, more I wanted to see how the current code we generate plays with F#, and it's... Ok 🤣
