### ISSUE TITLE
 Some TokenizerTests fail when regional format is using "," instead of "." for floating point number representation

### ISSUE THREAD

**Issue by minesworld** [tonybaloney/CSnakes#244]
CSnakes.Tests.TokenizerTests.ParseFunctionParameterDefaultDouble
   Source: TokenizerTests.cs line 158
   Duration: < 1 ms

  Message: 
Assert.Equal() Failure: Strings differ
             ↓ (pos 2)
Expected: "-1.1"
Actual:   "-1,1"
             ↑ (pos 2)

  Stack Trace: 
TokenizerTests.ParseFunctionParameterDefaultDouble() line 164
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

---

CSnakes.Tests.TokenizerTests.ParseFunctionParameterDefaultValuesNoType(value: "1.01")
   Source: TokenizerTests.cs line 125
   Duration: 3 ms

  Message: 
Assert.Equal() Failure: Strings differ
            ↓ (pos 1)
Expected: "1.01"
Actual:   "1,01"
            ↑ (pos 1)

  Stack Trace: 
TokenizerTests.ParseFunctionParameterDefaultValuesNoType(String value) line 131
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

---

CSnakes.Tests.TokenizerTests.ParseFunctionParameterDefaultValuesNoType(value: "-1.01")
   Source: TokenizerTests.cs line 125
   Duration: < 1 ms

  Message: 
Assert.Equal() Failure: Strings differ
             ↓ (pos 2)
Expected: "-1.01"
Actual:   "-1,01"
             ↑ (pos 2)

  Stack Trace: 
TokenizerTests.ParseFunctionParameterDefaultValuesNoType(String value) line 131
InvokeStub_TokenizerTests.ParseFunctionParameterDefaultValuesNoType(Object, Span`1)
MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by minesworld** [comment]
in `**PythonConstant.cs**` use **CultureInfo.InvariantCulture** as

```
public class Integer(long value) : PythonConstant
{
    public long Value { get; } = value;
    public override string ToString() => Value.ToString(CultureInfo.InvariantCulture);
}

  public sealed class Float(double value) : PythonConstant
  {
      public double Value { get; } = value;
      public override string ToString() => Value.ToString(CultureInfo.InvariantCulture);
  }
```

**Comment by tonybaloney** [comment]
@atifaziz you were working on constants, do you mind taking a look at a PR
