### ISSUE TITLE
Rename PyObject.Create to PyObject.Steal or Wrap

### ISSUE THREAD

**Issue by minesworld** [tonybaloney/CSnakes#265]
Code like 

`PyObject dict = PyObject.Create(Raw.PyDict_New());`

looks like the CPythons PyDictionary would get its refcount increased.

But it is stolen, which should be reflected in the function call:

`PyObject dict = PyObject.Steal(Raw.PyDict_New());`

While Wrap somehow might imply increasing the reference count:

`PyObject dict = PyObject.Wrap(pyObjectToHoldPtr);`

PS: already rewriting to the Raw class..

**Comment by tonybaloney** [comment]
All of these APIs are internal. `PyObject.Create` is always called with a pointer to an owned reference and is countered by the DecRef in the `Dispose` method.
Thanks for the suggestion, but I'm happy with the way it's named and it's an internal method and not part of the consumer APIs.

**Comment by minesworld** [comment]
> All of these APIs are internal. `PyObject.Create` is always called with a pointer to an owned reference and is countered by the DecRef in the `Dispose` method. Thanks for the suggestion, but I'm happy with the way it's named and it's an internal method and not part of the consumer APIs.

OK - different developer, different needs. For me CSnakes is a super exiting C# bridge. And from my experience using Python bridges, developers will have the need to call the CAPI if they are serious about getting the most out of it.

The beauty of CSnakes.Runtime.CAPI is - its usable as C code. And this no shortage of "how to" examples... Even better: SafeHandle makes it BETTER code the C by REDUCING the effort. MAGIC...

But such beauty can only shine if the Bridge is designed the right way. Wording is important - and finding the right one which is understood by CPython AND C# developers can be quite challenging.

I reasearched Scripting languages for some time now (even used SmallTalk - GlamorousToolkit, OMG...), but your bridge seems very, very promising.

If you have different targets for CSnakes - no problem. Its MIT. Just let me know if you want to tackle the "speed problem" too. Otherwise I will rename my fork. But that would be a shame, as I see a chance to change CPythons implementation too. If you're a Python Foundation fellow you might know the right people...

PS: another shame - that this is not a official Microsoft project.
