### ISSUE TITLE
Rename CSnakes to CSnake

### ISSUE THREAD

**Issue by minesworld** [tonybaloney/CSnakes#273]
**as it is Python and not Pythons...**

And my guess is - for the foreseeable future CSnakes will be only able to use **one** CPython at a time and not different version together in a single process.

As a non native english speaker there might be a reason that it is CSnakes, but in the real world non natives like me might be the superior number. (That might be not correct english...)

**Comment by tonybaloney** [comment]
Thanks for suggestion. I'm happy with the name as it is.

**Comment by minesworld** [comment]
OK - so we **must** support different version... 

Have thought about that already. "No problem" as dotnet can "import" C# sources at runtime. So every CPython Runtime API gets generated (if no version not there yet) - at runtime...
