### ISSUE TITLE
FromConda raises obscure exception when used with the folder instead of binary path

### ISSUE THREAD

**Issue by homerokzam** [tonybaloney/CSnakes#284]
Hi, 

Congratulations on this fantastic project! I’m really excited to see how it evolves.

However, I’m encountering an issue with my project where I’m unable to generate C# (.cs) code based on my Python code as expected. I’ve followed the instructions but couldn’t get the C# code generation to work properly.

Here is a link to my project on GitHub: https://github.com/homerokzam/dotnet-python .

Any help or guidance would be greatly appreciated!

Best regards,
Homero Kzam

**Comment by tonybaloney** [comment]
Here's a diff of the required changes to get your project working https://github.com/homerokzam/dotnet-python/pull/1

**Comment by homerokzam** [comment]
Thank you so much for the detailed feedback!

I want to sincerely apologize for my oversight with the <AdditionalFiles> tag. I didn’t realize it was incorrect (using “AdicionalFiles”) and should have been in English. That was definitely my mistake, and thank you so much for pointing that out!

After following your advice and correcting the project file, I was able to successfully compile the project, and I can’t thank you enough for the guidance. It really helped me move forward!

However, I’m now encountering a runtime error when trying to execute the project. The error message is as follows:
Exception has occurred: CLR/System.ComponentModel.Win32Exception
An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in System.Diagnostics.Process.dll: 'The FileName property should not be a directory unless UseShellExecute is set.'
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at CSnakes.Runtime.ProcessUtils.ExecuteCommand(ILogger logger, ProcessStartInfo startInfo)
   at CSnakes.Runtime.ProcessUtils.ExecuteCommand(ILogger logger, String fileName, String arguments)
   at CSnakes.Runtime.Locators.CondaLocator.ExecuteCondaCommand(String arguments)
   at CSnakes.Runtime.Locators.CondaLocator..ctor(ILogger logger, String condaBinaryPath)
   at CSnakes.Runtime.ServiceCollectionExtensions.<>c__DisplayClass9_0.<FromConda>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext
   
   Once again, thank you so much for your patience and help — it’s been instrumental in getting me this far!

Best regards

**Comment by homerokzam** [comment]
I found the issue! The problem was with the parameter in the .FromConda() method. The incorrect path was being used. The correct value for my environment is:

.FromConda("/opt/homebrew/Caskroom/miniconda/base/condabin/conda")

After updating it, the project runs as expected.

Thank you again for your help!

**Comment by tonybaloney** [comment]
That error message could be more helpful. I doubt you'll be the last person to confuse what that parameter should be
